#!/usr/bin/env php
<?php

use Cubex\Cubex;
use CubexBase\Application\Context\AppContext;
use MrEssex\CubexCli\CliWrapper;

$loader = require('vendor/autoload.php');

$app = Cubex::withCustomContext(AppContext::class, __DIR__, $loader);

CliWrapper::initialise($app);
CliWrapper::initialiseAlternativeRoot($app, 'mressex/cubex-translate');

exit($app->cli());
