<?php

use CubexBase\Application\Context\Seo\SeoManager;

/**
 * @var SeoManager $this
 */
?>

<?php if($this->get('description')): ?>
  <meta name="description" content="<?= $this->get('description') ?> ">
  <meta property="og:description" content="<?= $this->get('description') ?> ">
<?php endif ?>

<?php foreach($this->getMeta() as $meta): ?>
  <?php if($this->get($meta)): ?>
    <meta name="<?= str_replace('_', '-', $meta) ?>" content="<?= $this->get($meta) ?>">
  <?php endif; ?>
<?php endforeach; ?>

<?php foreach($this->getOgMeta() as $ogMeta): ?>
  <?php if($this->get($ogMeta)): ?>
    <meta name="<?= str_replace('_', ':', $ogMeta) ?>" content="<?= $this->get($ogMeta) ?>">
  <?php endif; ?>
<?php endforeach; ?>

<?php foreach($this->getTwitterMeta() as $twitterMeta): ?>
  <?php if($this->get($twitterMeta)): ?>
    <meta name="<?= str_replace('_', ':', $twitterMeta) ?>" content="<?= $this->get($twitterMeta) ?>">
  <?php endif; ?>
<?php endforeach; ?>
