<?php

use CubexBase\Application\Http\Layout\DefaultLayout\DefaultLayout;
use Packaged\Dispatch\Dispatch;
use Packaged\Dispatch\ResourceStore;

/**
 * @var DefaultLayout $this
 */

$ctx = $this->getContext();
$store = Dispatch::instance()->store();
?>
<!doctype html>
<html lang="<?= $ctx->currentLanguage() ?>">
<head>
  <meta charset="UTF-8">

  <link rel="icon" href="<?= $ctx->www('/favicon.ico?v=1.0') ?>">
  <link rel="icon" href="<?= $ctx->www('/icon.svg') ?>" type="image/svg+xml">
  <link rel="apple-touch-icon" href="<?= $ctx->www('/icon.png') ?>">
  <link type="text/plain" rel="author" href="<?= $ctx->www('/humans.txt') ?>">
  <link rel="manifest" href="<?= $ctx->www('/site.webmanifest') ?>">

  <?php if($this->seoProvider): ?>
    <?= $this->seoProvider ?>
  <?php endif; ?>

  <?= $store->generateHtmlIncludes() ?>
</head>

<body class="<?= $this->getPageClass() ?>">

<?php foreach($this->flash->getMessages() as $message): ?>
  <div class="alert alert-<?= $message['type'] ?>">
    <p><?= $message['message'] ?></p>
  </div>
<?php endforeach; ?>

<?= $this->getHeader() ?>
<?= $this->getContent() ?>
<?= $this->getFooter() ?>


<?= $store->generateHtmlIncludes(ResourceStore::TYPE_JS) ?>
</body>
</html>
