name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    name: PHP ${{ matrix.php }} Build

    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0' ]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: git config --global credential.helper store

      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: apcu
          coverage: none

      - run: composer install
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}

      - run: yarn build

  coverage:
    runs-on: ubuntu-latest

    name: Coverage Reporter

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: git config --global credential.helper store

      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: apcu
          coverage: xdebug

      - run: composer install
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}

      - run: composer run-script check

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}

      - run: yarn coverage


  lint:
    runs-on: ubuntu-latest

    name: Linter

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: git config --global credential.helper store

      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: apcu
          coverage: none

      - run: composer install
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH_JSON }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}

      - run: yarn lint
