name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Linter

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: apcu
          coverage: none

      - run: composer install

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: npm ci

      - run: npm run lint
