<?php

use CubexBase\Application\Layout\Layout;
use Packaged\Dispatch\Dispatch;
use Packaged\Dispatch\ResourceStore;

/**
 * @var Layout $this
 */

$store = Dispatch::instance()->store();
?>
<!doctype html>
<html lang="en">
<head>
  <title><?= $this->getContext()->seoMeta()->getTitle() ?></title>
  <meta charset="UTF-8">
  <?= $this->getContext()->seoMeta()->getDescription() ?>
  <?= $this->getContext()->seoMeta()->getKeywords() ?>
  <?= $this->getContext()->seoMeta()->getCanonical() ?>
  <?= $this->getContext()->seoMeta()->getRobots() ?>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= $store->generateHtmlIncludes(ResourceStore::TYPE_CSS, null, [ResourceStore::PRIORITY_LOW]) ?>
</head>
<body class="<?= $this->getPageClass() ?>">
<?= $this->getContent() ?>
<?= $store->generateHtmlIncludes(ResourceStore::TYPE_CSS, ResourceStore::PRIORITY_LOW) ?>
<?= $store->generateHtmlIncludes(ResourceStore::TYPE_JS) ?>
</body>
</html>
