<?php

use CubexBase\Application\Layout\Layout;
use Packaged\Dispatch\Dispatch;
use Packaged\Dispatch\ResourceStore;

/**
 * @var Layout $this
 */

$ctx = $this->getContext();
$store = Dispatch::instance()->store();
$flashes = $ctx->getFlashBag();
?>
<!doctype html>
<html lang="<?= $ctx->currentLanguage() ?>">
<head>
  <meta charset="UTF-8">

  <link rel="icon" href="<?= $ctx->linkBuilder('/favicon.ico?v=1.0') ?>">
  <link rel="icon" href="<?= $ctx->linkBuilder('/icon.svg') ?>" type="image/svg+xml">
  <link rel="apple-touch-icon" href="<?= $ctx->linkBuilder('/icon.png') ?>">
  <link type="text/plain" rel="author" href="<?= $ctx->linkBuilder('/humans.txt') ?>">
  <link rel="manifest" href="<?= $ctx->linkBuilder('/site.webmanifest') ?>">
  <title>Cubex Skeleton</title>

  <?= $store->generateHtmlIncludes(ResourceStore::TYPE_CSS, null, [ResourceStore::PRIORITY_LOW]) ?>
</head>

<body class="<?= $this->getPageClass() ?>">

<?php if($flashes->has('success')): ?>
  <?php foreach($flashes->get('success') as $message): ?>
    <div class="alert alert-success">
      <p><?= $message ?></p>
    </div>
  <?php endforeach; ?>
<?php endif; ?>

<?php if($ctx->getSession()->has('user')): ?>
  <div class="alert alert-info">
    <p>Logged in as <?= $ctx->getSession()->get('user') ?></p>
  </div>
<?php endif; ?>

<?= $this->getHeader() ?>
<?= $this->getContent() ?>
<?= $this->getFooter() ?>

<?= $store->generateHtmlIncludes(ResourceStore::TYPE_CSS, ResourceStore::PRIORITY_LOW) ?>
<?= $store->generateHtmlIncludes(ResourceStore::TYPE_JS) ?>
</body>
</html>
